### ISSUE TITLE
Route Matching

### ISSUE THREAD

**Issue by eliysha** [paullla/bolt-extension-infinite-scroll#5]
Hi,

I'm about to install this extension, but I wonder how route is detected ?
How Bolt will match this route `/infinitescroll` (see start.js) ?

Regards

**Comment by GwendolenLynch** [comment]
In the Bolt 2 version [here](https://github.com/paullla/bolt-extension-infinite-scroll/blob/v1.0.1/Extension.php#L11)

In master which is for Bolt v3 [here](https://github.com/paullla/bolt-extension-infinite-scroll/blob/master/src/InfiniteScrollExtension.php#L17) and [here](https://github.com/paullla/bolt-extension-infinite-scroll/blob/master/src/Controller/InfiniteScrollController.php#L30)

**Comment by eliysha** [comment]
Thanks for the quick reply :-)
